alertmanager:
  enabled: false
prometheusOperator:
  nodeSelector:
    node: ak-utils
prometheus:
  prometheusSpec:
    nodeSelector:
      node: ak-utils
    additionalScrapeConfigs:
      - job_name: 'hotel-res'
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          regex: 'hotel-res'
          action: keep
      - job_name: 'kubernetes-cadvisor'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
kube-state-metrics:
  nodeSelector:
    node: ak-utils
grafana:
  adminPassword: admin
  nodeSelector:
    node: ak-utils
