apiVersion: v1
kind: Namespace
metadata:
  name: kiali-operator
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kiali-operator
  namespace: kiali-operator
spec:
  interval: 24h
  url: https://kiali.org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: kiali-operator
spec:
  interval: 5m
  releaseName: kiali-operator
  chart:
    spec:
      chart: kiali-operator
      version: 1.43.0
      sourceRef:
        kind: HelmRepository
        name: kiali-operator
        namespace: kiali-operator
  values:
    namespace: kiali-operator
    nodeSelector:
      node: ak-panozzo-utils
    cr:
      create: true
      namespace: istio-system
      spec:
        auth:
          openid: {}
          openshift:
            client_id_prefix: kiali
          strategy: anonymous
        external_services:
          prometheus:
            namespace_label: "istio-system"
            url: "http://kube-prometheus-stack-kube-prometheus.monitoring:9090"
          grafana:
            namespace_label: "istio-system"
            url: "http://kube-prometheus-stack-grafana.monitoring:3000"
            in_cluster_url: "http://kube-prometheus-stack-grafana.monitoring:3000"
          custom_dashboards:
            enabled: true
          istio:
            component_status:
              components:
                - app_label: istio-ingressgateway
                  is_core: false
                  is_proxy: true
                  namespace: istio-ingress