apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recommendation-pvc
  namespace: hotel-res
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: recommendation-storage
  resources:
    requests:
      storage: 1Gi
